### PR TITLE
fixing some pep8 details

### PR DESCRIPTION
**Pull request by fchapoton**
Checklist
* [x] Added an entry in `doc/news/`.  (Ok. None needed.)
* [x] Added a test for this change. (Not part of the CI yet.)

### CODE REVIEW

**Comment by fchapoton** [comment]
the failure happens on a line tagged "random", that should be tagged "not tested" and the next line too

**Comment by fchapoton** [comment]
ping ?

**Comment by saraedum** [comment]
@videlec we should do something about these randomly failing Lyapunov exponents…

**Review by saraedum — APPROVED** [review]

**Review by saraedum — APPROVED** [review]

**Comment by videlec** [comment]
> @videlec we have to do something about these randomly failing Lyapunov exponents…namely:
> 
> ```
>  File "surface_dynamics/flat_surfaces/origamis/origami_dense.pyx", line 1826, in surface_dynamics.flat_surfaces.origamis.origami_dense.Origami_dense_pyx.?
> Failed example:
>     o.lyapunov_exponents_approx(involution=s, nb_iterations=2**21)  # abs tol .05
> Expected:
>     ([0.6000, 0.2000],
>      [0.8000, 0.4000])
> Got:
>     ([0.450016509703521, 0.150057924057956],
>      [0.599994117515633, 0.300090271196313])
> Tolerance exceeded in 3 of 4:
>     0.6000 vs 0.450016509703521, tolerance 2e-1 > 5e-2
>     0.8000 vs 0.599994117515633, tolerance 3e-1 > 5e-2
>     0.4000 vs 0.300090271196313, tolerance 1e-1 > 5e-2
> ```

I agree. One could ignore completely the values and just check consistency of the list sizes in the output?

**Pull request merged**
